### ISSUE TITLE
火山图FC

### ISSUE THREAD

**Issue by NorahYu97** [xiayh17/RNAseqStat#1]
enhance_volcano函数画火山图图时使用的横坐标为logFC，副标题中为啥又标为FC。
![图片](https://user-images.githubusercontent.com/86408344/173029475-042a9d1b-c6d7-4dae-a09b-a13145d4f95f.png)

**Comment by xiayh17** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    确实有问题，可以使用labs函数自行修改
        
    
        
            
        
    
    
         
        
            font{
            line-height: 1.6;
        }Best Regards,Yonghe Xia
        
    
     

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年6月10日 16:57
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [xiayh17/RNAseqStat] 火山图FC (Issue #1)
        
      
    
  
  

enhance_volcano函数画火山图图时使用的横坐标为logFC，副标题中为啥又标为FC。

**Comment by xiayh17** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    RNAseqStat 已经停止更新，或许可以试试它的全新版本RNAseqStat2
        
            https://github.com/xiayh17/RNAseqStat2
        
    
    
        
            
        
    
    
         
        
            font{
            line-height: 1.6;
        }Best Regards,Yonghe Xia
        
    
     

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年6月10日 16:57
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [xiayh17/RNAseqStat] 火山图FC (Issue #1)
        
      
    
  
  

enhance_volcano函数画火山图图时使用的横坐标为logFC，副标题中为啥又标为FC。
